### ISSUE TITLE
Convert X-Road service's WSDLs into XTR services

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/XTR#3]
AS AN Architect
I WANT X-Road service's WSDLs to be converted into XTR services
SO THAT they could be used as REST services

### Acceptance Criteria

- [ ] Use any of WSDLs from https://x-tee.ee/catalogue/EE as input
- [ ] Automatically generate sample requests for every XTR DSL
- [ ] XTR services can be used via its spefic DSL
- [ ] Any XTR DSL is also a REST endpoint

#### Scope

- [ ] [XTR services](https://github.com/orgs/buerokratt/projects/43/views/2)
